version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY=a2ey@rz+u^*$$(_hc9xzg)4k^-&mii6ho3wdbbqbr)$$tw)9*$$3& 
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
